# Generated by Django 5.2.7 on 2025-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(default='Nouvelle conversation', max_length=200),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='processing_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('USER', 'Message utilisateur'), ('BOT', 'Message bot'), ('SYSTEM', 'Message système')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='chatbot_cha_convers_a85429_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='chatbot_cha_timesta_d01b0b_idx'),
        ),
        migrations.AlterModelTable(
            name='chatconversation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
    ]
