# Generated by Django 5.2.6 on 2025-09-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=100)),
                ('classe', models.IntegerField()),
                ('type', models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Charge', 'Charge'), ('Produit', 'Produit'), ('TVA', 'TVA'), ('Autre', 'Autre')], max_length=20)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_ecriture', models.CharField(max_length=50)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.FloatField(default=0)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
        ),
    ]
