# Generated by Django 5.2.6 on 2025-10-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionline',
            name='compte',
        ),
    ]
