# Generated by Django 5.2.6 on 2025-10-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='solde_initial',
            new_name='soldeInitial',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='numero_ecriture',
            new_name='numeroEcriture',
        ),
        migrations.RenameField(
            model_name='transactionline',
            old_name='calculated_amount',
            new_name='calculatedAmount',
        ),
    ]
