# Generated by Django 5.2.6 on 2025-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_transactionline_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='compte',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
