# Generated by Django 5.2.6 on 2025-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_solde_initial_account_soldeinitial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionline',
            old_name='account',
            new_name='accountId',
        ),
        migrations.AddField(
            model_name='transactionline',
            name='accountName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
