# Generated by Django 5.2.6 on 2025-10-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_account_transactionline_accountid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionline',
            old_name='accountId',
            new_name='account',
        ),
    ]
