# Generated by Django 5.2.6 on 2025-10-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_transactionline_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionline',
            name='compte',
        ),
    ]
