# Generated by Django 5.2.6 on 2025-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_accountid_transactionline_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='compte',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
