# Generated by Django 5.2.6 on 2025-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transactionline_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Actif/Passif', 'Actif/Passif'), ('Charge', 'Charge'), ('Produit', 'Produit'), ('TVA', 'TVA'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
